const countries = {
    "en-GB": "English (UK)",
    "en-US": "English (US)",
    "hi-IN": "Hindi (India)",
    "fr-FR": "French (France)",
    "es-ES": "Spanish (Spain)",
    "de-DE": "German (Germany)",
    "it-IT": "Italian (Italy)",
    "ja-JP": "Japanese (Japan)",
    "ko-KR": "Korean (South Korea)",
    "zh-CN": "Chinese (Simplified, China)",
    "zh-TW": "Chinese (Traditional, Taiwan)",
    "ar-SA": "Arabic (Saudi Arabia)",
    "pt-PT": "Portuguese (Portugal)",
    "pt-BR": "Portuguese (Brazil)",
    "ru-RU": "Russian (Russia)",
    "tr-TR": "Turkish (Turkey)",
    "nl-NL": "Dutch (Netherlands)",
    "sv-SE": "Swedish (Sweden)",
    "pl-PL": "Polish (Poland)",
    "fi-FI": "Finnish (Finland)",
    "no-NO": "Norwegian (Norway)",
    "da-DK": "Danish (Denmark)",
    "cs-CZ": "Czech (Czech Republic)",
    "el-GR": "Greek (Greece)",
    "he-IL": "Hebrew (Israel)",
    "th-TH": "Thai (Thailand)",
    "vi-VN": "Vietnamese (Vietnam)",
    "id-ID": "Indonesian (Indonesia)",
    "ms-MY": "Malay (Malaysia)",
    "ro-RO": "Romanian (Romania)",
    "hu-HU": "Hungarian (Hungary)",
    "uk-UA": "Ukrainian (Ukraine)"
};
